vita: abstract platform policy hooks and add LiveArea/icon packaging

diff --git a/build/vita/Makefile b/build/vita/Makefile
--- a/build/vita/Makefile
+++ b/build/vita/Makefile
@@ -30,6 +30,9 @@ include ../common_toolchain.mk
 
 VITA_TITLE ?= Chocolate Keen
 VITA_TITLE_ID ?= CHKN00001
+VITA_ICON ?= ../../assets/vita/icon0.png
+VITA_PIC0 ?= ../../assets/vita/pic0.png
+VITA_LIVEAREA_CONTENTS_DIR ?= ../../assets/vita/livearea/contents
 VELF_PATH=chocolate-keen.velf
 SELF_PATH=eboot.bin
 VPK_PATH=chocolate-keen-vita.vpk
@@ -73,6 +76,20 @@ $(VPK_PATH): $(SELF_PATH)
 	mkdir -p $(DIST_ROOT)/sce_sys $(DIST_ROOT)/GAMEDATA
 	cp $(SELF_PATH) $(DIST_ROOT)/eboot.bin
 	vita-mksfoex -s TITLE_ID=$(VITA_TITLE_ID) "$(VITA_TITLE)" $(DIST_ROOT)/sce_sys/param.sfo
+	if [ -f $(VITA_ICON) ]; then \
+		cp $(VITA_ICON) $(DIST_ROOT)/sce_sys/icon0.png; \
+	else \
+		echo "Missing Vita icon: $(VITA_ICON)"; \
+		echo "Add a 128x128 PNG at that path or override VITA_ICON=..."; \
+		exit 1; \
+	fi
+	if [ -f $(VITA_PIC0) ]; then \
+		cp $(VITA_PIC0) $(DIST_ROOT)/sce_sys/pic0.png; \
+	fi
+	if [ -d $(VITA_LIVEAREA_CONTENTS_DIR) ]; then \
+		mkdir -p $(DIST_ROOT)/sce_sys/livearea; \
+		cp -r $(VITA_LIVEAREA_CONTENTS_DIR) $(DIST_ROOT)/sce_sys/livearea/; \
+	fi
 	if [ -f ../linux/chocolate-keen.cfg ]; then \
 		cp ../linux/chocolate-keen.cfg $(DIST_ROOT)/chocolate-keen.cfg; \
 	else \
